import { expect, test } from '@playwright/test';
import { startSyntheticWorkout, openBenchPress, openSetNotes } from './setup';
import { readPersistence } from './persistence';

test('compact logger records time, bodyweight, per-side and loaded work without changing pending work', async ({ page }, info) => {
  await startSyntheticWorkout(page);
  const seconds = page.getByLabel('Segundos de la serie 1', { exact: true });
  await expect(seconds).toHaveValue('60');
  await expect(page.getByLabel('Carga de la serie 1', { exact: true })).toHaveCount(0);
  const box = await seconds.boundingBox();
  const dock = await page.getByTestId('workout-command-bar').boundingBox();
  expect(box).not.toBeNull(); expect(dock).not.toBeNull();
  expect(box!.y + box!.height).toBeLessThan(dock!.y);
  expect(dock!.y + dock!.height).toBeLessThanOrEqual(732);
  await page.screenshot({ path: info.outputPath('compact-time-360.png') });
  await seconds.fill('45');
  await page.getByRole('button', { name: 'Completar serie 1', exact: true }).click();
  await page.getByRole('button', { name: 'Deshacer completado de la serie 1', exact: true }).click();
  await expect(page.getByText('COMPLETADA', { exact: true })).toHaveCount(0);
  await expect(seconds).toHaveValue('45');
  await page.getByRole('button', { name: 'Completar serie 1', exact: true }).click();
  await page.getByRole('button', { name: 'Siguiente ejercicio', exact: true }).click();
  await expect(page.getByLabel('Repeticiones de la serie 1', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Carga de la serie 1', { exact: true })).toHaveCount(0);
  await openBenchPress(page);
  await page.getByLabel('Carga de la serie 1', { exact: true }).fill('60');
  await page.getByLabel('Repeticiones de la serie 1', { exact: true }).fill('8');
  await (await openSetNotes(page, 1)).fill('Synthetic compact record');
  await page.getByRole('button', { name: 'Completar serie 1', exact: true }).click();
  await page.getByRole('button', { name: 'Editar serie 2', exact: true }).click();
  await expect(page.getByLabel('RIR de la serie 1', { exact: true })).toHaveCount(0);
  await expect(page.getByLabel('RIR de la serie 2', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Omitir serie 2', exact: true }).click();
  await page.getByLabel('Motivo para omitir la serie 2', { exact: true }).fill('Synthetic omission');
  await page.getByRole('button', { name: 'Confirmar omisión de la serie 2', exact: true }).click();
  await page.reload();
  await expect(page.getByLabel('Carga de la serie 1', { exact: true })).toHaveValue('60');
  await expect(page.getByLabel('RIR de la serie 2', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Siguiente ejercicio', exact: true }).click();
  await page.getByRole('button', { name: 'Siguiente ejercicio', exact: true }).click();
  await expect(page.getByText('Reps / lado', { exact: true }).first()).toBeVisible();
  await expect(page.getByLabel('Carga de la serie 1', { exact: true })).toHaveCount(0);
  await expect.poll(async () => JSON.parse(String((await readPersistence(page, info)).workouts[0]!.actual_snapshot_json)).activeExerciseIndex).toBe(4);
  const before = await readPersistence(page, info);
  const actual = JSON.parse(String(before.workouts[0]!.actual_snapshot_json));
  expect(actual.exercises[0]).toMatchObject({ recording: 'seconds', sets: [expect.objectContaining({ seconds: '45', load: '', reps: '', disposition: 'COMPLETED' }), expect.objectContaining({ disposition: 'PENDING' })] });
  await page.getByRole('button', { name: 'Revisar y terminar entrenamiento', exact: true }).click();
  await expect(page.getByTestId('finish-review')).toContainText('2 completadas · 1 omitida · 11 pendientes');
  await page.getByRole('button', { name: 'Seguir entrenando', exact: true }).click();
  expect((await readPersistence(page, info)).workouts).toEqual(before.workouts);
  await page.getByRole('button', { name: 'Revisar y terminar entrenamiento', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar fin de entrenamiento', exact: true }).click();
  await expect(page).toHaveURL(/4179\/$/);
  await page.reload();
  const after = await readPersistence(page, info);
  expect(after.workouts[0]!.status).toBe('COMPLETED');
  const finished = JSON.parse(String(after.workouts[0]!.actual_snapshot_json));
  expect(finished.completionMode).toBe('early');
  expect(finished.exercises).toEqual(actual.exercises);
  expect(after.sessionSnapshots).toEqual(before.sessionSnapshots);
});
