import { test, expect } from '@playwright/test';
import { readPersistence } from './persistence';
import { changeCycleFixture } from './cycle-fixture';
import { startSyntheticWorkout } from './setup';

test('personal setup resumes a separate draft and only activates on confirmation', async ({ page, context }, info) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Crear mi plan', exact: true }).click();
  await page.getByRole('radio', { name: 'Fuerza', exact: true }).click();
  await page.getByRole('radio', { name: 'Entreno con regularidad', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(page.getByText('Tus tres días', { exact: true })).toBeVisible();
  await expect(page.getByText('Borrador local · sin activar', { exact: true })).toBeVisible();
  const draft = await readPersistence(page, info);
  expect(draft.cycles).toHaveLength(0);
  expect(draft.settings.find(row => row.key === 'training-settings')).toBeUndefined();
  await page.close();
  const app = await context.newPage(); await app.goto('/');
  await app.getByRole('button', { name: 'Crear mi plan', exact: true }).click();
  await expect(app.getByText('Tus tres días', { exact: true })).toBeVisible();
  await app.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(app.getByText('Tu gimnasio', { exact: true })).toBeVisible();
  await app.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(app.getByText('Tus referencias', { exact: true })).toBeVisible();
  await app.getByRole('button', { name: 'Ver mi plan', exact: true }).click();
  await expect(app.getByText('Tu plan está listo', { exact: true })).toBeVisible();
  await expect(app.getByText('Borrador local · sin activar', { exact: true })).toBeVisible();
  const preview = await readPersistence(app, info);
  expect(preview.cycles).toHaveLength(0);
  await app.getByRole('button', { name: 'Guardar y salir', exact: true }).click();
  await app.getByRole('button', { name: 'Crear mi plan', exact: true }).click();
  await expect(app.getByText('Tu plan está listo', { exact: true })).toBeVisible();
  await app.getByRole('button', { name: 'Activar mi plan', exact: true }).click();
  await expect(app.getByTestId('cycle-progress-band')).toBeVisible();
  const activated = await readPersistence(app, info);
  expect(activated.cycles.filter(row => row.status === 'ACTIVE')).toHaveLength(1);
  expect(activated.cycles[0]?.kind).toBe('strength');
  expect(activated.templates).toHaveLength(1);
  expect(JSON.stringify(activated.sessionSnapshots)).not.toContain('calculatedLoad');
  await app.reload();
  await expect(app.getByTestId('cycle-progress-band')).toBeVisible();
  expect(await readPersistence(app, info)).toEqual(activated);
  await app.screenshot({ path: info.outputPath('first-personal-plan.png') });
});

test('known decimal reference survives demo and a failed activation rolls back before a single retry', async ({ page, context }, info) => {
  await page.goto('/setup');
  await page.getByRole('radio', { name: 'Entreno con regularidad', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Lunes', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(page.getByText('Elige exactamente tres días de entrenamiento.', { exact: true })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Martes', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('radio', { name: 'Conozco mi referencia de Press banca', exact: true }).click();
  await page.getByLabel('Referencia de Press banca', { exact: true }).fill('60,');
  await page.getByRole('button', { name: 'Guardar y salir', exact: true }).click();
  await page.getByRole('button', { name: 'Crear mi plan', exact: true }).click();
  await expect(page.getByLabel('Referencia de Press banca', { exact: true })).toHaveValue('60,');
  await page.getByRole('button', { name: 'Ver mi plan', exact: true }).click();
  await expect(page.getByText(/Press banca: escribe/)).toBeVisible();
  await page.getByLabel('Referencia de Press banca', { exact: true }).fill('60,5');
  await page.getByRole('button', { name: 'Guardar y salir', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Crear mi plan', exact: true })).toBeVisible();
  const personal = await readPersistence(page, info);
  await page.goto('/settings');
  await page.getByRole('button', { name: 'Probar demo', exact: true }).click();
  await page.getByRole('button', { name: 'Entrar en demo', exact: true }).click();
  await expect(page.getByText('DEMO · DATOS DE EJEMPLO', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Salir de la demo', exact: true }).click();
  await expect(page.getByText('DEMO · DATOS DE EJEMPLO', { exact: true })).toHaveCount(0);
  expect(await readPersistence(page, info)).toEqual(personal);
  await page.goto('/setup');
  await expect(page.getByLabel('Referencia de Press banca', { exact: true })).toHaveValue('60,5');
  await page.getByRole('button', { name: 'Ver mi plan', exact: true }).click();
  await page.getByRole('button', { name: /Martes ·/ }).click();
  await expect(page.getByText(/48.75 kg/).first()).toBeVisible();
  await page.screenshot({ path: info.outputPath('known-plan-preview.png') });
  const before = await readPersistence(page, info);
  let app = await changeCycleFixture(page, context, info, db => db.exec("CREATE TRIGGER fail_setup BEFORE INSERT ON session_plan BEGIN SELECT RAISE(ABORT, 'Synthetic write failure'); END"));
  await app.goto('/setup');
  await app.getByRole('button', { name: 'Activar mi plan', exact: true }).click();
  await expect(app.getByText(/No se pudo guardar/)).toBeVisible();
  expect(await readPersistence(app, info)).toEqual(before);
  app = await changeCycleFixture(app, context, info, db => db.exec('DROP TRIGGER fail_setup'));
  await app.goto('/setup');
  await app.getByRole('button', { name: 'Activar mi plan', exact: true }).evaluate(element => { (element as HTMLElement).click(); (element as HTMLElement).click(); });
  await expect(app.getByTestId('cycle-progress-band')).toBeVisible();
  const after = await readPersistence(app, info);
  expect(after.templates).toHaveLength(1);
  expect(after.cycles.filter(row => row.status === 'ACTIVE')).toHaveLength(1);
  const settings = JSON.parse(String(after.settings.find(row => row.key === 'training-settings')!.value_json));
  expect(settings.profile.benchPressReference).toBe(60.5);
  expect(settings.schedule).toEqual([2, 3, 5]);
  await app.goto('/setup');
  await expect(app.getByText('Ya tienes un plan activo. Tus entrenamientos se conservan.')).toBeVisible();
  expect(await readPersistence(app, info)).toEqual(after);
});

test('goal and returning experience change the real plan without re-onboarding existing work', async ({ page }, info) => {
  await page.goto('/setup');
  await page.getByRole('radio', { name: 'Hipertrofia', exact: true }).click();
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Ver mi plan', exact: true }).click();
  await expect(page.getByText('Reentrada · 2 semanas', { exact: true })).toBeVisible();
  await expect(page.getByText('Hipertrofia · 4 semanas', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Activar mi plan', exact: true }).click();
  await expect(page.getByTestId('cycle-progress-band')).toBeVisible();
  const state = await readPersistence(page, info);
  expect(state.cycles.map(row => [row.kind, row.status])).toEqual([['hypertrophy', 'READY'], ['reentry', 'ACTIVE']]);
  await page.goto('/setup');
  await expect(page.getByRole('button', { name: 'Ver mi plan', exact: true })).toBeVisible();
  expect(await readPersistence(page, info)).toEqual(state);
});

test('opening setup with recorded work preserves the existing workout and settings', async ({ page }, info) => {
  await startSyntheticWorkout(page);
  const before = await readPersistence(page, info);
  await page.goto('/setup');
  await expect(page.getByText('Ya tienes un plan activo. Tus entrenamientos se conservan.')).toBeVisible();
  expect(await readPersistence(page, info)).toEqual(before);
});

test('saved preference changes require an explicit draft refresh and update the real preview', async ({ page }, info) => {
  await page.goto('/setup');
  await page.getByRole('radio', { name: 'Entreno con regularidad', exact: true }).click();
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Ver mi plan', exact: true }).click();
  await page.getByRole('button', { name: 'Guardar y salir', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Crear mi plan', exact: true })).toBeVisible();
  await page.goto('/settings');
  await page.getByLabel('Conozco mi referencia de Press banca', { exact: true }).click();
  await page.getByLabel('Referencia de Press banca', { exact: true }).fill('100');
  await page.getByRole('button', { name: 'Guardar configuración local', exact: true }).click();
  await expect(page.getByText('Configuración guardada en este dispositivo.')).toBeVisible();
  await page.goto('/setup');
  await page.getByRole('button', { name: 'Activar mi plan', exact: true }).click();
  await expect(page.getByText(/La configuración o el plan cambió/)).toBeVisible();
  expect((await readPersistence(page, info)).cycles).toHaveLength(0);
  await page.getByRole('button', { name: 'Usar preferencias guardadas', exact: true }).click();
  await page.getByRole('button', { name: /Lunes ·/ }).click();
  await expect(page.getByText(/80 kg/).first()).toBeVisible();
  await page.getByRole('button', { name: 'Activar mi plan', exact: true }).click();
  await expect(page.getByTestId('cycle-progress-band')).toBeVisible();
  const state = await readPersistence(page, info);
  expect(JSON.stringify(state.sessionSnapshots)).toContain('calculatedLoad');
  expect(JSON.parse(String(state.settings.find(row => row.key === 'training-settings')!.value_json)).profile.benchPressReference).toBe(100);
});

test('incompatible equipment identifies the repair instead of reporting a write failure', async ({ page }, info) => {
  await page.goto('/setup');
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('radio', { name: 'Solo peso corporal', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Ver mi plan', exact: true }).click();
  await expect(page.getByText(/Requisito 1/).first()).toBeVisible();
  expect((await readPersistence(page, info)).cycles).toHaveLength(0);
  await page.getByRole('button', { name: 'Atrás', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Barra', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Banco', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Ver mi plan', exact: true }).click();
  await expect(page.getByText('Tu plan está listo', { exact: true })).toBeVisible();
});

test('a conflicting draft write has deliberate cancel and reload recovery', async ({ page }, info) => {
  await page.addInitScript(() => {
    const post = Worker.prototype.postMessage;
    Worker.prototype.postMessage = function(message, transfer) {
      const state = window as unknown as { conflictDraft?: boolean };
      if (state.conflictDraft && message.type === 'prepare' && String(message.data?.source).includes('UPDATE app_setting SET value_json') && String(message.data?.source).includes('NOT EXISTS')) {
        delete state.conflictDraft;
        message.data.source = message.data.source.replace('WHERE key = ?', 'WHERE 0 AND key = ?');
      }
      post.call(this, message, Array.isArray(transfer) ? { transfer } : transfer);
    };
  });
  await page.goto('/setup');
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(page.getByText('Tus tres días', { exact: true })).toBeVisible();
  await expect(page.getByText('Borrador local · sin activar', { exact: true })).toBeVisible();
  const saved = await readPersistence(page, info);
  await page.evaluate(() => { (window as unknown as { conflictDraft: boolean }).conflictDraft = true; });
  await page.getByRole('checkbox', { name: 'Lunes', exact: true }).click();
  await expect(page.getByText(/La configuración o el plan cambió/)).toBeVisible();
  expect(await readPersistence(page, info)).toEqual(saved);
  await page.getByRole('button', { name: 'Recargar borrador guardado', exact: true }).click();
  await page.getByRole('button', { name: 'Conservar mis cambios', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Lunes', exact: true })).toHaveAttribute('aria-checked', 'false');
  await page.getByRole('button', { name: 'Recargar borrador guardado', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar recarga', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Lunes', exact: true })).toHaveAttribute('aria-checked', 'true');
  await page.getByRole('checkbox', { name: 'Lunes', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Martes', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(page.getByText('Tu gimnasio', { exact: true })).toBeVisible();
});
