import { expect, test } from '@playwright/test';
import { readPersistence } from './persistence';
import { openBenchPress } from './setup';

test('personal first use and later preference previews preserve active work across restart', async ({ page, context }, info) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Crear mi plan', exact: true }).click();
  await page.getByRole('radio', { name: 'Fuerza', exact: true }).click();
  await page.getByRole('radio', { name: 'Entreno con regularidad', exact: true }).click();
  for (let step = 0; step < 3; step++) await page.getByRole('button', { name: 'Continuar', exact: true }).click();
  await page.getByRole('button', { name: 'Ver mi plan', exact: true }).click();
  await page.getByRole('button', { name: 'Activar mi plan', exact: true }).click();
  await expect(page.getByTestId('cycle-progress-band')).toBeVisible();
  await page.getByRole('button', { name: 'Revisar preparación para entrenar', exact: true }).click();
  await page.getByLabel('Dolor de 0 a 2, estable', { exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar preparación', exact: true }).click();
  await expect(page.getByTestId('workout-screen')).toBeVisible();
  await openBenchPress(page);
  await page.getByLabel('Carga de la serie 1', { exact: true }).fill('40');
  await page.getByLabel('Repeticiones de la serie 1', { exact: true }).fill('5');
  await page.getByRole('button', { name: 'Completar serie 1', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Deshacer completado de la serie 1', exact: true })).toBeVisible();
  const original = await readPersistence(page, info);
  await page.goto('/plan');
  await page.getByRole('button', { name: 'Abrir configuración del plan', exact: true }).click();
  for (const day of ['Lun', 'Mié', 'Vie', 'Mar', 'Jue', 'Sáb']) await page.getByLabel(`Alternar día ${day}`, { exact: true }).click();
  await page.getByLabel('Alternar equipo Banco inclinado', { exact: true }).click();
  await page.getByLabel('Conozco mi referencia de Press banca', { exact: true }).click();
  await page.getByLabel('Referencia de Press banca', { exact: true }).fill('60,5');
  await page.getByRole('button', { name: 'Guardar configuración local', exact: true }).click();
  await expect(page.getByText('Configuración guardada en este dispositivo.')).toBeVisible();
  const saved = await readPersistence(page, info);
  expect({ ...saved, settings: original.settings }).toEqual(original);
  await page.getByRole('button', { name: 'Volver a Hoy', exact: true }).click();
  await page.getByRole('button', { name: 'Ver vista previa de preferencias', exact: true }).click();
  for (const day of ['Martes', 'Jueves', 'Sábado']) await expect(page.getByRole('button', { name: `${day}, vista previa de preferencias`, exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Martes, vista previa de preferencias', exact: true }).click();
  await expect(page.getByText('48.75 kg', { exact: true }).first()).toBeVisible();
  await page.screenshot({ path: info.outputPath('saved-preference-preview.png'), fullPage: true });
  expect(await readPersistence(page, info)).toEqual(saved);
  await page.goto('/workout');
  await page.getByRole('button', { name: 'Reemplazar ejercicio', exact: true }).click();
  await page.getByRole('radio', { name: 'Equipo no disponible', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Elegir Press inclinado con mancuernas', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
  expect(await readPersistence(page, info)).toEqual(saved);
  await page.goto('/settings');
  await page.getByLabel('Usar solo peso corporal', { exact: true }).click();
  await page.getByRole('button', { name: 'Quitar requisito 3', exact: true }).click();
  await page.getByRole('button', { name: 'Quitar requisito 2', exact: true }).click();
  await page.getByLabel('Elegir Bird-dog para requisito 1', { exact: true }).click();
  await page.getByLabel('Alternar restricción Demanda abdominal baja', { exact: true }).click();
  await page.getByLabel('Alternar restricción Sin impacto', { exact: true }).click();
  await page.getByRole('button', { name: 'Guardar configuración local', exact: true }).click();
  await expect(page.getByText('Configuración guardada en este dispositivo.')).toBeVisible();
  const restricted = await readPersistence(page, info);
  expect({ ...restricted, settings: original.settings }).toEqual(original);
  await page.close();
  const reopened = await context.newPage();
  await reopened.goto('/plan');
  await reopened.getByRole('button', { name: 'Ver vista previa de preferencias', exact: true }).click();
  await reopened.getByRole('button', { name: 'Martes, vista previa de preferencias', exact: true }).click();
  await expect(reopened.getByText('Bird-dog', { exact: true }).first()).toBeVisible();
  await expect(reopened.getByText('48.75 kg', { exact: true })).toHaveCount(0);
  expect(await readPersistence(reopened, info)).toEqual(restricted);
});
