import { test, expect } from '@playwright/test';
import { readPersistence } from './persistence';

for (const width of [360, 390, 430]) test(`Today at ${width}px keeps preparation visible and opens the selected exercise after preparation`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 732 });
  // A deterministic Sunday tests calendar presentation, never persisted history.
  await page.clock.setFixedTime(new Date(2026, 8, 20, 12));
  await page.goto('/');
  await expect(page.getByText('Todavía no hay un plan activo', { exact: true })).toBeVisible();
  await page.goto('/plan');
  await page.getByRole('button', { name: 'Crear vista previa del ciclo', exact: true }).click();
  await page.getByRole('button', { name: 'Activar plan confirmado', exact: true }).click();
  await expect(page.getByText('Plan activo', { exact: true })).toBeVisible();
  await page.goto('/');
  await expect(page.getByTestId('today-calendar-status')).toContainText('Hoy: descanso');
  await expect(page.getByText('domingo, 20 de septiembre', { exact: true })).toBeVisible();
  const preparation = page.getByRole('button', { name: 'Revisar preparación para entrenar', exact: true });
  const bounds = await preparation.boundingBox();
  expect(bounds).not.toBeNull();
  expect(bounds!.y).toBeGreaterThanOrEqual(0);
  expect(bounds!.y + bounds!.height).toBeLessThan(660);
  await page.screenshot({ path: info.outputPath(`today-rest-${width}.png`) });
  const before = await readPersistence(page, info);
  await page.getByRole('button', { name: 'Abrir ejercicio 3: Press banca', exact: true }).click();
  await expect(page.getByTestId('readiness-focused-surface')).toBeVisible();
  expect((await readPersistence(page, info)).workouts).toEqual(before.workouts);
  await page.getByRole('radio', { name: 'Dolor de 0 a 2, estable', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar preparación', exact: true }).click();
  await expect(page.getByTestId('workout-sequence-rail')).toHaveAttribute('aria-valuenow', '3');
  await expect.poll(async () => JSON.parse(String((await readPersistence(page, info)).workouts[0]!.actual_snapshot_json)).activeExerciseIndex).toBe(2);
  await expect(page).toHaveURL(/\/workout$/);
  await page.getByRole('button', { name: 'Siguiente ejercicio', exact: true }).click();
  await expect(page.getByTestId('workout-sequence-rail')).toHaveAttribute('aria-valuenow', '4');
  await page.reload();
  await expect(page.getByTestId('workout-sequence-rail')).toHaveAttribute('aria-valuenow', '4');
  await page.getByRole('button', { name: 'Cerrar entrenamiento', exact: true }).click();
  await expect(page.getByTestId('today-resume')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Continuar entrenamiento', exact: true })).toBeVisible();
  await page.goto('/plan');
  const second = page.getByRole('button', { name: /Semana 2 de Reentrada/ });
  await second.click();
  await expect(second).toHaveAttribute('aria-expanded', 'true');
  const selected = await readPersistence(page, info);
  expect(selected.sessionSnapshots).toEqual(before.sessionSnapshots);
  expect(selected.settings.find(row => row.key === 'plan-week-selection')?.value_json).toBe('"reentry-draft-2"');
  await page.goto('/settings');
  await page.goBack();
  await expect(second).toHaveAttribute('aria-expanded', 'true');
  await page.reload();
  await expect(second).toHaveAttribute('aria-expanded', 'true');
  await second.scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath(`plan-selected-${width}.png`) });
});

test('an exercise entry cannot bypass a saved blocking preparation', async ({ page }, info) => {
  await page.goto('/plan');
  await page.getByRole('button', { name: 'Crear vista previa del ciclo', exact: true }).click();
  await page.getByRole('button', { name: 'Activar plan confirmado', exact: true }).click();
  await expect(page.getByText('Plan activo', { exact: true })).toBeVisible();
  await page.goto('/');
  await page.getByRole('button', { name: 'Abrir ejercicio 3: Press banca', exact: true }).click();
  await page.getByRole('radio', { name: 'Dolor sobre 4, creciente o señal de alerta', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Confirmar preparación', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Cerrar Preparación de hoy', exact: true }).click();
  await page.reload();
  await expect(page.getByTestId('readiness-focused-surface')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Confirmar preparación', exact: true })).toHaveCount(0);
  const before = await readPersistence(page, info);
  await page.goto('/workout?exercise=2');
  await expect(page.getByText('No se pudo abrir el entrenamiento', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Completar serie 1', exact: true })).toHaveCount(0);
  expect((await readPersistence(page, info)).workouts).toEqual(before.workouts);
});
