import { expect, test } from '@playwright/test';
import { startSyntheticWorkout, openBenchPress, openSetNotes } from './setup';
import { readPersistence } from './persistence';

test('optional rest and selected row survive navigation and cold reopen with elapsed wall-clock time', async ({ page, context }, info) => {
  const start = Date.parse('2026-09-20T12:00:00Z');
  await page.clock.setFixedTime(start);
  await startSyntheticWorkout(page);
  await openBenchPress(page);
  await page.getByLabel('Carga de la serie 1', { exact: true }).fill('60');
  await page.getByLabel('Repeticiones de la serie 1', { exact: true }).fill('8');
  await page.getByRole('switch', { name: 'Descanso automático al completar una serie', exact: true }).click();
  await page.getByRole('button', { name: 'Completar serie 1', exact: true }).click();
  await expect(page.getByTestId('mini-rest-timer')).toContainText('01:30');
  await page.getByRole('button', { name: 'Editar serie 2', exact: true }).click();
  await (await openSetNotes(page, 2)).fill('Synthetic resume draft');
  await expect.poll(async () => JSON.parse(String((await readPersistence(page, info)).workouts[0]!.actual_snapshot_json)).activeSetIndex).toBe(1);
  const before = await readPersistence(page, info);
  const initial = JSON.parse(String(before.workouts[0]!.actual_snapshot_json));
  expect(initial.timer.runningSince).toBe(start);
  await page.clock.setFixedTime(start + 30_000);
  await page.getByRole('button', { name: 'Cerrar entrenamiento', exact: true }).click();
  await page.getByRole('button', { name: 'Continuar entrenamiento', exact: true }).click();
  await expect(page.getByLabel('RIR de la serie 2', { exact: true })).toBeVisible();
  await expect(page.getByTestId('mini-rest-timer')).toContainText('01:00');
  await page.close();
  const reopened = await context.newPage();
  await reopened.clock.setFixedTime(start + 60_000);
  await reopened.goto('/workout');
  await expect(reopened.getByLabel('RIR de la serie 2', { exact: true })).toBeVisible();
  await expect(reopened.getByTestId('mini-rest-timer')).toContainText('00:30');
  const restored = JSON.parse(String((await readPersistence(reopened, info)).workouts[0]!.actual_snapshot_json));
  expect(restored.exercises).toEqual(initial.exercises);
  expect(restored.timer).toEqual(initial.timer);
  expect(restored.activeExerciseIndex).toBe(initial.activeExerciseIndex);
  expect(restored.activeSetIndex).toBe(1);
  await reopened.getByRole('button', { name: 'Pausar descanso', exact: true }).click();
  await reopened.clock.setFixedTime(start + 80_000);
  await reopened.getByRole('button', { name: 'Añadir 30 segundos al descanso', exact: true }).click();
  await expect(reopened.getByTestId('mini-rest-timer')).toContainText('01:00');
  await reopened.screenshot({ path: info.outputPath('rest-and-active-row.png') });
  await reopened.getByRole('button', { name: 'Continuar descanso', exact: true }).click();
  await reopened.clock.setFixedTime(start + 100_000);
  await expect(reopened.getByTestId('mini-rest-timer')).toContainText('00:40');
  await reopened.getByRole('button', { name: 'Omitir descanso', exact: true }).click();
  await expect(reopened.getByTestId('mini-rest-timer')).toHaveCount(0);
  await reopened.reload();
  await expect(reopened.getByLabel('RIR de la serie 2', { exact: true })).toBeVisible();
  await expect(reopened.getByTestId('mini-rest-timer')).toHaveCount(0);
  expect((await readPersistence(reopened, info)).sessionSnapshots).toEqual(before.sessionSnapshots);
});
